export const streets = [
    "Ady Endre utca",
    "Akácfa utca",
    "Alma utca",
    "Almáskert utca",
    "Andy Vajna utca",
    "Aradi vértanúk tere",
    "Arany János utca",
    "Attila út",
    "Árpád utca",
    "Bajcsy-Zsilinszky utca",
    "Baross Gábor utca",
    "Báthory István utca",
    "Béke utca",
    "Bódi László \"Cipő\" emléksétány",
    "Becskereki utca",
    "Bem utca",
    "Bessenyei köz",
    "Bessenyei utca",
    "Bihari János utca",
    "Bocskai utca",
    "Bolgár utca",
    "Burgundi utca",
    "Csalogány utca",
    "Csillag köz",
    "Csillag utca",
    "Csokonai utca",
    "Damjanich dűlő",
    "Damjanich utca",
    "Darusziget utca",
    "Dózsa György út",
    "Deák Ferenc utca",
    "Diófás utca",
    "Diner István utca",
    "Dobó István utca",
    "Dohányos utca",
    "Domb utca",
    "Dombköz utca",
    "Egres dűlő",
    "Epreskert utca",
    "Erzsébet utca",
    "Esze Tamás utca",
    "Fáy András utca",
    "Fürdő utca",
    "Flórián tér",
    "Gagarin utca",
    "Gülbaba utca",
    "Gyár utca",
    "Gyár utcai lakótelep",
    "Halasy Gyula utca",
    "Hármas út",
    "Háromszéki utca",
    "Hársfa utca",
    "Homokkert utca",
    "Hulics utca",
    "Hunyadi utca",
    "Ipar utca",
    "Ipari utca",
    "Iskola tér",
    "Jéki út",
    "Jókai utca",
    "Jósa András utca",
    "József Attila utca",
    "Kastal utca",
    "Kákástó utca",
    "Kölcsey utca",
    "Körte utca",
    "Keleti elkerülő út",
    "Kereszt utca",
    "Kinizsi Pál utca",
    "Kiss János utca",
    "Kisvárda keleti elkerülő",
    "Kodály Zoltán utca",
    "Kossuth Lajos utca",
    "Krudy park",
    "Krucsay Márton utca",
    "Labanc utca",
    "Liliom utca",
    "Liptay Béla út",
    "Litki út",
    "Madách utca",
    "Magyar utca",
    "Malom köz",
    "Margaréta utca",
    "Mária utca",
    "Mártírok útja",
    "Mátyás király utca",
    "Móricz Zsigmond utca",
    "Mózer Ernő utca",
    "Mester utca",
    "Mező utca",
    "Mikszáth Kálmán utca",
    "Munkás utca",
    "Nagyboldogasszony utca",
    "Nagymező dűlő",
    "Nagymező utca",
    "Nap utca",
    "Nyáry Pál utca",
    "Ostrom utca",
    "Pacsirta utca",
    "Papi út",
    "Petőfi Sándor utca",
    "Piac utca",
    "Rákóczi utca",
    "Rétalja utca",
    "Rigó Jancsi utca",
    "Sántha István utca",
    "Sárköz utca",
    "Sörgyár utca",
    "Serház utca",
    "Simonyi utca",
    "Somogyi Rezső utca",
    "Sorompó utca",
    "Sport utca",
    "Stadion utca",
    "Szabadság utca",
    "Szabolcs vezér út",
    "Széchenyi utca",
    "Szív utca",
    "Szüret utca",
    "Szennyvíztelepi út",
    "Szent György tér",
    "Szent György utca",
    "Szent László utca",
    "Szeszfőzde út",
    "Szőlőskert köz",
    "Szőlőskert utca",
    "Tavasz utca",
    "Táncsics utca",
    "Tátra utca",
    "Török utca",
    "Temesvár utca",
    "Toldi Miklós utca",
    "Tompa Mihály utca",
    "Tompos úti lakótelep",
    "Tompos utca",
    "Tordai utca",
    "Tulipán utca",
    "Vasút utca",
    "Vasvári Pál utca",
    "Vay Ádám utca",
    "Váci Mihály utca",
    "Vár utca",
    "Vár zug",
    "Váralja utca",
    "Várday István park",
    "Várday István utca",
    "Várday köz",
    "Várkert utca",
    "Városháza köz",
    "Városmajor út",
    "Városmajor utca",
    "Váry Emil utca",
    "Vásár tér",
    "Víz utca",
    "Vörösmarty Mihály tér",
    "Vigadó utca",
    "Virágh Ferenc utca",
    "Wesselényi utca",
    "Zrínyi tér",
    "Zsigmond utca"
]